version: "3.8"
services:
  app:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${db-name}
      DB_MYSQL_PASSWORD: ${db-password}
      DB_MYSQL_NAME: ${db-name}
    volumes:
      - data:/data
      - letsEncrypt:/etc/letsencrypt
  db:
    image: "jc21/mariadb-aria:latest"
    environment:
      MYSQL_ROOT_PASSWORD: ${db-password}
      MYSQL_DATABASE: ${db-name}
      MYSQL_USER: ${db-name}
      MYSQL_PASSWORD: ${db-password}
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  data:
  letsEncrypt:
  mysql-data:
